apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mock-services-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: mock-services-pv