apiVersion: v1
kind: PersistentVolume
metadata:
  name: mock-services-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mock-services
