apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mock-services-deploy
  name: mock-services-svc
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: mock-services-pod
  type: NodePort
status:
  loadBalancer: {}
