springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

logging:
  file:
    name: application.log
    path: /logs/
  level:
    root: info
    org.springframework: warn
    org.hibernate: error
    com.mycompany.api: info