springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

server:
  ssl:
    enabled: ${tomcat_ssl_enabled:false}
    key-store: ${tomcat_key_store_path}
    key-store-password: ${tomcat_key_store_pwd}
    key-store-type: ${tomcat_key_store_type}
    key-alias: ${tomcat_key_store_alias}

logging:
  file:
    name: application.log
    path: /logs/
  level:
    root: info
    org.springframework: warn
    org.hibernate: error
    com.mycompany.api: info